### ISSUE TITLE
Mac crashes with cache_memory(algo = "spookyhash")

### ISSUE THREAD

**Issue by instantkaffee** [r-lib/memoise#101]
I want to use the fast spookyhash algo (supported by digest).

Calling `digest(o, algo = "spookyhash")` works fine.
But memoizing using the parameter `cache = cache_memory(algo = "spookyhash")` crashes my Mac.

```
library(digest)
library(memoise)

# Larger object
o= runif(n = 1e6)
prettyunits::pretty_bytes(object.size(o))

# Works fine
digest(o, algo = "spookyhash")

# Setup function
slow_function= function(x= o){x}
fast_function= memoise::memoise(slow_function, cache = cache_memory(algo = "spookyhash"))

# Crashes
fast_function()

```

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.6

**Comment by jimhester** [comment]
I am almost 100% sure this is a bug in the digest package, and the appropriate input will reproduce it. But I don't really have time to discover the appropriate input now. I would suggest using _any_ of the other algorithms in digest other than spookyhash.

It is crashing at https://github.com/eddelbuettel/digest/blob/a596ca386d01e0e2bc27a5ea07e467372eb4d29a/src/spooky_serialize.cpp#L67

**Comment by instantkaffee** [comment]
Thats a pitty: In this case I cannot use memoise, as the speedup is eaten up by all hashing algo even with xxhash. I will swith to [memo package](https://cran.r-project.org/web/packages/memo/index.html) as it can fast, lightweight handle reference pointer key lookup, which is sufficient in my case.
