### ISSUE TITLE
Any timeline for next release?

### ISSUE THREAD

**Issue by sz-cgt** [r-lib/memoise#107]
Just wondering when we could expect an official 1.1.1 release.

While I can use `remotes::install_github()` for personal use, my DevOps people don't care for that in productive settings

**Comment by jimhester** [comment]
Is there something in particular you want from the devel version?

**Comment by sz-cgt** [comment]
The `drop_cache()` capability

**Comment by hclimente** [comment]
Sorry to bother you, but is there any update in this regard? I used `drop_cache()` in [my package](https://github.com/hclimente/martini). But if it's not coming online soon, I'll have to drop `memoise` entirely, since Bioconductor won't accept dependencies from Github.

**Comment by jimhester** [comment]
memoise 2.0.0 is on CRAN as of yesterday.
