### ISSUE TITLE
Creating a memoised function via pipe

### ISSUE THREAD

**Issue by jeffkeller-einc** [r-lib/memoise#148]
Anonymous functions can be memoised like so:

```r
myfun <- memoise::memoise(function(x) {x + 1})
class(myfun)
[1] "memoised" "function"
```

However, it would be convenient to be able to use a pipe (native or `magrittr`) to do this. Like the above example, it would avoid creating an intermediate object but it would also make the code more readable (especially if the function spans many lines).

But this doesn't seem to work:

```r
myfun <- function(x) {x + 1} |> memoise::memoise()
class(myfun)
# [1] "function"
```

**Comment by wch** [comment]
I think the problem in your example is due to how R parses the code.  Notice that the body of `myfun` actually contains the `|>` operator:

```R
myfun <- function(x) {x + 1} |> memoise::memoise()
myfun
#> function(x) {x + 1} |> memoise::memoise()
```

This is equivalent to:

```R
function(x) memoise::memoise({ x + 1})
```

So you need to add parentheses around the function definition:

```R
myfun <- (function(x) {x + 1}) |> memoise::memoise()
myfun
#> Memoised Function:
#> function(x) {x + 1}
class(myfun)
#> [1] "memoised" "function"
```
