### ISSUE TITLE
memoise cache seems to be invalidated when re-knitting

### ISSUE THREAD

**Issue by jonovik** [r-lib/memoise#45]
I'm hoping to speed up re-knitting an rmarkdown document using `memoise(cache=cache_filesystem(...`. Unfortunately, the cache seems to be invalidated every time I re-knit. However, caching *does* work when I run my code in a plain `Rgui` session outside of RStudio/knitr. Small reproducible example (`test_memoise.Rmd`):

    ---
    output: html_document
    ---
    
    ```{r}
    library(memoise)
    cache <- cache_filesystem("~/test_memoise")
    fun <- function(input) {Sys.sleep(1); return(input)}
    fun.mem <- memoise(fun, cache=cache)
    system.time(sapply(1:2, fun.mem))
    system.time(sapply(1:2, fun.mem))
    ```

**What I would expect:** The last two lines should take around 2 and 0 seconds, respectively, on first knitting. When re-knitting both lines should take negligible time.

**What happens instead:** Every knitting behaves like the first one.

    system.time(sapply(1:2, fun.mem))
    ##    user  system elapsed 
    ##    0.03    0.01    2.05
    system.time(sapply(1:2, fun.mem))
    ##    user  system elapsed 
    ##       0       0       0

**But it works in plain Rgui:**

    > library(memoise)
    > cache <- cache_filesystem("~/Dropbox/.rcache/test_memoise")
    > fun <- function(input) {Sys.sleep(1); return(input)}
    > fun.mem <- memoise(fun, cache=cache)
    > system.time(sapply(letters, fun.mem))
       user  system elapsed 
       0.06    0.00    0.06 

This is on RStudio 1.0.143 and Windows 10.

```
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Europe/Berlin               
 date     2017-05-18                  

Packages --------------------------------------------------------------------------------------------------
 package   * version     date       source                          
 base      * 3.4.0       2017-04-21 local                           
 compiler    3.4.0       2017-04-21 local                           
 datasets  * 3.4.0       2017-04-21 local                           
 devtools    1.13.1.9000 2017-05-18 Github (hadley/devtools@ad6f28e)
 digest      0.6.12      2017-01-27 CRAN (R 3.4.0)                  
 graphics  * 3.4.0       2017-04-21 local                           
 grDevices * 3.4.0       2017-04-21 local                           
 knitr       1.15.1      2016-11-22 CRAN (R 3.4.0)                  
 memoise   * 1.1.0       2017-04-21 CRAN (R 3.4.0)                  
 methods   * 3.4.0       2017-04-21 local                           
 pkgbuild    0.0.0.9000  2017-05-18 Github (r-pkgs/pkgbuild@8aab60b)
 pkgload     0.0.0.9000  2017-05-18 Github (r-pkgs/pkgload@119cf9a) 
 rlang       0.1.1       2017-05-18 Github (hadley/rlang@684221a)   
 stats     * 3.4.0       2017-04-21 local                           
 tools       3.4.0       2017-04-21 local                           
 utils     * 3.4.0       2017-04-21 local                           
 withr       1.0.2       2016-06-20 CRAN (R 3.4.0)  
```

**Comment by jonovik** [comment]
The cache is also used correctly when executing the chunk inside the RStudio console (Control-Shift-Enter).

**Comment by nzbart** [comment]
I'm seeing the same behaviour. I can run the same code in a normal R session, and the cache will generate the same hash every run, even when I restart R. However, when I knit my document, a new hash is generated every time, and a new file drops out into the cache directory.
