### ISSUE TITLE
default arguments of a memoised function can't be updated

### ISSUE THREAD

**Issue by bluaze** [r-lib/memoise#49]
in commit 03566bb4 and after, if a memoised function is updated by default arguments using formals<-, and then evaluated by a set of arguments that not cached yet, the default arguments eventually fed to the body of the function are the original ones, not the updated ones.  

that is because when a memoised function is actually evaluated instead of fetched from cache, the funciton actually evaluated is _f in a manually constructed environment, not the memoised function itself, and the _f's default arguments will not be updated when updating the memoised function's arguments.  

it's not a problem in v1.1.0 as the whole set of arguments including explicitly given by user and implicitly given by defaults will be transferred to _f, but it's not the case in 03566bb4 as only arguments caught by match.call() will be transferred to _f.

**Comment by egnha** [comment]
Could you kindly demonstrate this issue with a concrete example? That would be helpful.

**Comment by jimhester** [comment]
So you are changing the formals of a function after memoising it? That seems to be an error prone approach I would not recommend and it is not something I think we want to invest resources in supporting.
