### ISSUE TITLE
(Re)initialize file system cache if it does not exist.

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/memoise#51]
```r
library(memoise)
f = memoise(rnorm, cache = cache_filesystem("cache"))
dir.create("new_dir")
setwd("new_dir")
f(1) 
## Error in gzfile(file, mode) : cannot open the connection 
## In addition: Warning message: 
## In gzfile(file, mode) :
##    cannot open compressed file 'cache/75bed0259340d03b', 
##    probable reason 'No such file or directory'
```

Users may also want to write packages with already-memoised functions, and the users of those packages could call the functions from any working directory.

**Comment by jimhester** [comment]
Would be best if we just use absolute rather than relative paths when we create the cache initially.

**Comment by wlandau-lilly** [comment]
Seems like that would cover the majority of use cases.

**Comment by hadley** [comment]
Was fixed in https://github.com/r-lib/memoise/commit/3a06c2c33c2b1b932656c9db832484dbba3a7b69
