### ISSUE TITLE
Limit memory usage in a cache

### ISSUE THREAD

**Issue by PeterNSteinmetz** [r-lib/memoise#53]
Would it be possible to have a form of the memory cache that will only use a specific amount of memory or store a particular number of recent function/argument combinations? This strikes me as possibly useful when looping over very large datasets and computing the same expensive object for multiple numbers of elements in the dataset. 

If one just caches all the expensive objects the cache will be become very large (is there any garbage collection on cached objects?). One often needs only the most recent function/argument combination if the arguments are ordered in this type of looping over a dataset.

I suppose a replacement for the memory cache which used a linked list of function/argument combinations rather than a hash set could work.

**Comment by wlandau-lilly** [comment]
Sounds handy. Could it use the file system for large/abandoned objects and memory for small/recent ones? Clearly, size is an easier metric than frequency of use. A [complete workflow dependency network](https://github.com/wlandau-lilly/drake) would let you [identify and discard objects you no longer need](https://github.com/wlandau-lilly/drake/blob/master/R/envir.R#L20), but this may be outside the scope of `memoise`.

**Comment by PeterNSteinmetz** [comment]
For a lot of uses I have in processing analysis over large datasets, even a cache of one set would be quite useful.

Consider analysis of a set of experiments where there are multiple specimens per experiment. The data is loaded on an experiment basis from some files which is expensive and there are many specimens in each experiment. If one loops over these from a listing in a dataframe using something like ddply from the plyr package, the load function for the data would be called many times for the same experiment. But if the load function is memoized with just a single item in the cache, that reloading is eliminated. At the same time, the single element cache avoids the problem of memory growing larger and larger as the results for specimens are collected.

The obvious extension is to have a linked list with more than one set of key-value pairs to cover cases where the repeat interval might be longer.

**Comment by mbertolacci** [comment]
Just a little bump on this issue. There is an open pull request that addresses it by adding a new cache, `cache_fixed_size`, which wraps another cache (by default `cache_memory`), and which drops a key/value pair when the size limit is exceeded.

**Comment by wch** [comment]
Closing because this functionality was added in the recent release of memoise, version 2.0.0.
