### ISSUE TITLE
Exclude certain parameters from memoisation

### ISSUE THREAD

**Issue by hschult** [r-lib/memoise#54]
Hey everyone,
I really like the idea of caching results to use them later as it promises to increase the performance significantly.
But I ran into a problem so let's say I have the following function:
```
myFunction <- function(a, b, sep){
   return(paste(a, b, sep =sep))
}
```
So if I memoise this function each time one of the arguments is changed it will create a new cache so it won't need to rerun in the future. But now what if the argument sep doens't really matter to me as it doesn't really affects the result besides a changed seperator.
Is there a way to exclude it so that there will be only a new cache if a or b changes and not sep?
Or if not will this be a feature in an upcoming version?

Thanks in advance for help

**Comment by dracodoc** [comment]
I think this behavior will not be intended result by `memoise` definition. You result is different anyway.

You can create a wrapper function that fix the changed parameters, if there is not many variations of parameter. 

```r
myFunction_space <- function(a, b){
   return(paste(a, b, sep =" "))
}
myFunction_comma <- function(a, b){
   return(paste(a, b, sep =","))
}
```

Then you can memoise the wrapper function. This is cumbersome but I don't think there is a better solution.

**Comment by hschult** [comment]
Thanks for the answer,
this code was just to explain what I wanted to do in reality I'm developing a shiny app and tried to memoise the callModule function. But nevermind in the meantime I finally managed to overcome my performance issues so I don't need to memoise anymore.

**Comment by dracodoc** [comment]
I'm not sure if `callModule` can be memoised. I think `memoise` should only be used on pure functions, i.e. no side effect, same input always get same output. `callModule` seemed to do something about reactive, which could be side effect.

**Comment by hschult** [comment]
I think you are right. At that time it sounded like a good idea to me to cache initialized modules but as I think about it now it would probably screw up the connection between UI and server so that the server won't recognize the UI belonging to it.

**Comment by wlandau-lilly** [comment]
My use case:

```
process_inputs(stuff_that_matters, jobs){
   mclapply(stuff_that_matters, process_one_input, mc.cores = jobs)
}
```

It makes total sense to ignore `jobs`. Also, I am assuming `stuff_that_matters` is long and `process_one_input` is too fast to be worth memoizing. On my HPC system, lots of tiny writes to a file system cache would actually slow things down quite a lot, so I would much rather memoize `process_inputs()` itself.

**Comment by dapperjapper** [comment]
Referencing #75 because I believe these are the same idea. This is a useful addition and I'm grateful someone built it!
