### ISSUE TITLE
Can I use same folder as filesystem cache for multiple memoised functions?

### ISSUE THREAD

**Issue by dracodoc** [r-lib/memoise#56]
@hadley  This is a usage question. I decided to post it here instead of SO because it's a very easy question for package author, though difficult to know for other users. 

For convenience I'd like to use same folder as filesystem cache for several functions (I need to save and restore folder later), but I'm not sure if different memoised functions cache will interfere with each other.

From the source code, it seemed that `forget` a memoised function will clear all content under the cache folder. So I guess I'm supposed to use different folder for different functions?

**Comment by karldw** [comment]
@dracodoc, I'm just another user here, but you're right.  `memoise` doesn't track which caches it creates, so can't clean up individual files when it's asked to `forget`.

On the other hand, it seems manageable to have a function that creates a new sub-cache for each function.
```r
my_memoise <- function(f, cache_dir = path_to_your_cache, ...) {
  fn_name <- deparse(substitute(f))
  subcache <- file.path(cache_dir, fn_name)
  memoise(f, ..., cache = cache_filesystem(subcache))
}
```

**Comment by jimhester** [comment]
Yeah my suggestion would to put the memoized functions in a parent folder, or write your own `cache_filesystem()` variant which does exactly what you are looking for.
