### ISSUE TITLE
path in caching backends should be absolute

### ISSUE THREAD

**Issue by wch** [r-lib/memoise#65]
For example, with `cache_filesystem`, if `path` is relative and the working directory changes, then the caching operations will happen in the wrong directory.

**Comment by jimhester** [comment]
Agreed, I even suggested this in https://github.com/r-lib/memoise/issues/51#issuecomment-319993161, but apparently never did anything about it :)

**Comment by xhdong-umd** [comment]
If I'm understanding correctly, https://github.com/xhdong-umd/memoise/commit/b237c97f8f68e2b3aa44351cbaeb8482bf828db1 should work. I run the tests in package and all passed.

`?normalizePath` mentioned about this, but I'm not sure if this will cause a problem.

> The canonical form of paths may not be what you expect. For example, on macOS absolute paths such as ‘/tmp’ and ‘/var’ are symbolic links.

If you think it's OK I can create a pull request.

**Comment by jimhester** [comment]
Just using normalizePath is ok, thanks for offering to do a pull request!
