### ISSUE TITLE
save/load file system cache to memory?

### ISSUE THREAD

**Issue by xhdong-umd** [r-lib/memoise#72]
I'm using parallel version of a memoised function (something like `parallel::mclapply`). 

I need to use file system cache across sessions, but file system cache will not be available for every thread. Since `mclapply` will fork current session, I think memory cache will work for them.

One solution will be load file system cache into memory in beginning, and save memory cache into file system when exiting (of course there need to be a proper exit process in user code otherwise it will not be saved.). This should be possible and also can provide some performance boost for normal file system cache usage.

**Comment by jimhester** [comment]
This might be a good idea, but I think this is unlikely to happen, so I will close this issue.
