### ISSUE TITLE
Support partial memory

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/memoise#74]
Useful package 👍 For some applications, some parameters are not relevant for the output of the function, because they define *how* the function performs a certain task, not *what* it does. Simple example: A http request. Arguments such as timeout, waiting time between requests etc. does influence the output of the function, but only the behavior at runtime. So it would be nice if I could specify which arguments are relevant for caching. Would that functionality fit into this package?

Transferred from coolbutuseless/memoisetools#1.

**Comment by jimhester** [comment]
Closed by #75
