### ISSUE TITLE
cache_memory() vs cache_filesystem()

### ISSUE THREAD

**Issue by pat-s** [r-lib/memoise#77]
In my use case 
- `cache_memory()` does not work
- `cache_filesystem()` works

Are there any restrictions to `cache_memory()`? I am calling a parallel wrapper function. However, I am running it sequentially.

**Comment by jimhester** [comment]
R uses process parallelism, not threads, the process do not share memory so naturally the memory cache will not work.

**Comment by pat-s** [comment]
Thanks!
