### ISSUE TITLE
Trying to get getSymbols to work

### ISSUE THREAD

**Issue by AndreMikulec** [r-lib/memoise#80]
Based on this.

unmemoise function? #36

I am trying to memoize quantmod::getSymbols.
However, I can not get it to work.

What else do I need to do?

```r
library(memoise)
library(quantmod)

sum.cache <- cache_memory()
is.memoised(getSymbols)
# [1] FALSE
getSymbols <- memoize(getSymbols, cache = sum.cache)
is.memoised(getSymbols)
# [1] TRUE
has_cache(getSymbols)("IBM")
# [1] FALSE
has_cache(getSymbols)("IBM", auto.assign = F)
# [1] FALSE
ibm <- getSymbols("IBM", auto.assign = F)
is.memoised(getSymbols)
# [1] TRUE
has_cache(getSymbols)("IBM", auto.assign = F)
# [1] FALSE
```

Thanks,
Andre

**Comment by jimhester** [comment]
The issue I think is `quantmod::getSymbols()` has an `env = parent.frame()` argument, and the parent frame environment is changing in between calls to `getSymbols()`.

**Comment by AndreMikulec** [comment]
Thanks.  @jimhester 
I will look into that.
