### ISSUE TITLE
Functions with identical body but different enclosing environments

### ISSUE THREAD

**Issue by bluaze** [r-lib/memoise#84]
To solve #38, which is different functions have same parameters (including empty parameter), body of the function to be memoised is introduced in digest in 70d959b2
To solve #58 #61, which is srcref will differ across sources, including different computers, body of the function is converted to character in 611cfadb

However, when two functions are identical except of their enclosing environments, problem arises

fn <- function(x) function(y) x+y

digest::digest(fn(1))
digest::digest(fn(2))

digest::digest(body(fn(1)))
digest::digest(body(fn(2)))

As examples above demonstrate, the two functions have different digests themselves, but identical digest of the bodies

As there is a function called removeSource in utils, which exactly removes all source related attributes of a function, it might be appropriate to use removeSource(fn) instead of as.character(body(fn))

digest::digest(utils::removeSource(fn(1)))
digest::digest(utils::removeSource(fn(2)))

**Comment by jimhester** [comment]
Good, suggestion! Want to create a Pull Request with this change?

**Comment by bluaze** [comment]
if enclosing environment is introduced in hashing function to be memoisd, not just body, functions relies on their enclosing environments will caching rightly. but functions that doesn't rely on enclosing environment might behave unexpectedly, as show below

```
test_env <- new.env()

evalq({
  fn <- function(x) { x+1 }
  
  i <- 0
  cat(digest::digest(removeSource(fn)),"\n")
  
  i <- 1
  cat(digest::digest(removeSource(fn)),"\n")
  
},test_env)
```

Although fn doesn't rely on any values in test_env, the digest changes as an irrelevant variant i changes. however, if these code execute in global environment directly, the digest won't change, as serialize used by digest underlying wouldn't serialize the global environment.

memoization might be more suit for functions that are referentially transparent, so it could not be appropriate to support functions rely on enclosing environment
