### ISSUE TITLE
Results of memoised function that returns a data.table are modifiable by reference

### ISSUE THREAD

**Issue by gnguy** [r-lib/memoise#90]
When returning a data.table from a memoised function, the stored memoised result is also modified by data.table operations such as `:=` that [subassign values by reference](https://stackoverflow.com/questions/10225098/understanding-exactly-when-a-data-table-is-a-reference-to-vs-a-copy-of-another#). While this data.table attribute of modification-by-reference is somewhat common knowledge with data.table users, I wouldn't have expected this behavior for data.tables returned by memoise, perhaps naively assuming that the results stored via memoise would be compartmentalized from any resulting operations. 

Copying the function output fixes the issue, as does using the filesystem instead of memory cache (see below for an example). However, I worry that new users may not realize that the memoized results, if they output data.tables or other objects that can be modified by reference, can modify the actual memoized results after they have already been produced. Additionally, this causes a discrepancy between results depending on the caching method used (memory vs. filesystem)

Is there any way to tweak the memoise function or the in-memory environment for cache_memory to allow memoise to keep data.table results fixed rather than subject to accidental modification by reference later on in a script?

```
library(data.table)
library(memoise)

base_function <- function() {
  return(data.table(x = 1:2, y = 2:3))
}

## Base memoise that returns modified data.table rather than function output
memoised_function <- memoise::memoise(base_function)
data <- memoised_function()
print(data)
data[, z := 2]
data2 <- memoised_function()

## Using copy to avoid in-place modification issues
forget(memoised_function)
data3 <- copy(memoised_function())
data3[, z := 2]
data4 <- memoised_function()

## Filesystem cache returns different result than in-memory cache
memoised_filesystem <- memoise::memoise(base_function, cache = cache_filesystem(tempdir()))
data5 <- memoised_filesystem()
data5[, z := 2]
data6 <- memoised_filesystem()
```
```
> print(data2)
   x y z
1: 1 2 2
2: 2 3 2
> print(data4)
   x y
1: 1 2
2: 2 3
> print(data6)
   x y
1: 1 2
2: 2 3
```

Addendum: I did notice this closed issue: https://github.com/r-lib/memoise/issues/21 but that issue related to using a memoised function within a data.table, while this one is referring to behavior when memoise returns a data.table.

**Comment by jimhester** [comment]
This seems outside the scope of memoise to me, I don't think special casing data.table results is something we want to do. You can however define a custom cache for your own use to explicitly copy them if you want.

**Comment by gnguy** [comment]
Thanks for your response, Jim. In R, are there other types of objects that are modifiable via reference for which this issue (and potential fix) would also be applicable? Or would any potential fix really be special casing for data.table? My hope would have been if there was some way to isolate the in-memory result through tweaking its environment or some other generalized solution rather than something tailored specifically for data.table, but unfortunately I don't know enough about R's in-memory behavior to know where to go from there.

I think the data.table user-case is somewhat important given its popularity and how well memoise fits nicely with some of its functions, for example, I could see many people memoising `fread` to avoid repetitive file loads, and not realizing this potential issue could affect their results. However, if you think that any fix within memoise itself would still be outside of scope, I also understand that and am fine closing this issue.

**Comment by jimhester** [comment]
The only other place with reference semantics in R is environments.

I think the only thing we could do in memoise is to include a type of cache which always copies its output to a new object when it is retrieved.
