### ISSUE TITLE
Can we invalidate the invalid cached data?

### ISSUE THREAD

**Issue by jmw86069** [r-lib/memoise#98]
I am using memoise to cache results from a network request. When the network request fails (it will always eventually fail) `NULL` results get cached.

I can check for invalid data returned from the memoised function, in my opinion the validation is outside the scope of memoise, and in the hands of the user. But how can the cache for one invalid result be cleared?

I might be missing a recommended strategy, this seems like a common risk.

Related to #39 

It appears the only current solution is to run `forget()` to remove the entire cache, very costly for one mistake.

What about `forget_cache(f, ...)` with the same syntax as `has_cache()`, it checks for, then deletes, existing cache.

Thanks in advance!

**Comment by jmw86069** [comment]
I now see there is a closed pull request #78 from October 2018, which appears to address this request.

What is the anticipated timeline for releasing the new version of memoise? (Actual question: Should I use the Github version, if this priority is relatively low?) Thanks again for help and pointers!

**Comment by jimhester** [comment]
There is no current timeline for a CRAN release, if you need the feature I would suggest you use the GitHub version.

**Comment by jmw86069** [comment]
Thanks for the speedy reply! For what it's worth, I've been testing the Github version and so far it seems to be working well!

A Wiki or expert tips and tricks guide would be really helpful for memoise. I've learned that reading the closed/opened issues is a good way to pick up advanced techniques, but I feel like I'm making the same early mistakes a lot of people before me have solved. No critique at all, the package works great! And I'm willing to help contribute for what it's worth. But if there's a queue for future blog posts, using memoise in an R-shiny context might be timely.
